$version: "2"

namespace com.aws.solutions.deepracer

/// Bulk-invite up to 200 racers by email. The trigger validates the request, creates a tracking
/// job (status PROCESSING), and starts a Step Functions execution that — per entry — creates a
/// Cognito account, assigns the Racer group, and sends the invitation email. Returns 202
/// immediately with the job id to poll via GetBulkInviteUserJobStatus. Admin-only.
@http(method: "POST", uri: "/profiles/bulkInvite", code: 202)
operation BulkInviteUser {
    input := {
        @required
        profiles: BulkInviteEntryList

        /// Client-supplied idempotency token (Idempotency standard). A retry carrying the same
        /// token returns the original job instead of creating a duplicate. Smithy's generated
        /// clients auto-populate this with a UUID v4 when the caller doesn't supply one, so the
        /// pattern MUST accept that format (a Nano ID pattern here would reject every
        /// auto-generated token and make the operation permanently unusable — see incident: every
        /// BulkInviteUser call failed API Gateway request validation with 400 Invalid request
        /// body). The value is used only to detect/dedupe retries; the job's own id (`jobId`,
        /// returned in the response) is independently generated by the backend and is NOT
        /// required to equal this token.
        @idempotencyToken
        @pattern("^[A-Za-z0-9-]{1,64}$")
        clientToken: String
    }

    output := {
        @required
        jobId: BulkInviteJobId

        @required
        status: BulkInviteJobStatus

        @required
        totalEntries: NonNegativeInteger
    }

    errors: [
        BadRequestError
        ConflictError
        InternalFailureError
        NotAuthorizedError
    ]
}

/// Return the current state of a bulk invite job for polling. Scoped to the requesting
/// admin's profile. `progress` is derived client-side as processedCount / totalEntries.
@readonly
@http(method: "GET", uri: "/profiles/bulkInvite/{jobId}")
operation GetBulkInviteUserJobStatus {
    input := {
        @required
        @httpLabel
        jobId: BulkInviteJobId
    }

    output := {
        @required
        status: BulkInviteJobStatus

        @required
        totalEntries: NonNegativeInteger

        @required
        processedCount: NonNegativeInteger

        @required
        createdCount: NonNegativeInteger

        @required
        skippedCount: NonNegativeInteger

        @required
        failedCount: NonNegativeInteger

        /// Per-entry outcomes, populated incrementally as the job progresses.
        results: BulkInviteResultList

        /// Set only when the job itself failed (state-machine-level error, per the Catch block).
        errorMessage: String
    }

    errors: [
        BadRequestError
        NotFoundError
        NotAuthorizedError
    ]
}

/// List the requesting admin's recent bulk invite jobs, most recent first. Backs the frontend's
/// active-job-detection fallback when local storage is unavailable. Scoped to the
/// requesting admin's profile. Admin-only.
///
/// Intentionally not `@paginated`: the result is naturally size-limited (Pagination standard,
/// Guidance #1 exception). At most one job per admin is active at a time; imports are infrequent
/// and records self-expire after 90 days (TTL), and the DAO returns only the most recent 20. The
/// caller only needs the newest job to resume polling — this is not a history-browse API.
@readonly
@http(method: "GET", uri: "/profiles/bulkInvite")
operation ListBulkInviteUserJobs {
    output := {
        @required
        jobs: BulkInviteJobSummaryList
    }

    errors: [
        NotAuthorizedError
    ]
}

/// Resend the Cognito invitation email to a user who has not yet accepted it (i.e. still in
/// FORCE_CHANGE_PASSWORD state). Non-idempotent: each call issues a new temporary password, so
/// this operation is intentionally NOT marked @idempotent. Admin-only.
@http(method: "POST", uri: "/profiles/{profileId}/resendInvite")
operation ResendInvite {
    input := {
        @required
        @httpLabel
        profileId: ResourceIdentifier
    }

    output := {
        @required
        message: String
    }

    errors: [
        BadRequestError
        ConflictError
        InternalFailureError
        NotFoundError
        NotAuthorizedError
    ]
}
